# Generated by Django 4.1.4 on 2024-05-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_users_pages_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='pages_per_day',
        ),
        migrations.AddField(
            model_name='users',
            name='api_key',
            field=models.CharField(max_length=50, null=True, verbose_name='Ключ'),
        ),
    ]
