# Generated by Django 4.1.4 on 2024-05-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_remove_users_pages_per_day_users_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='about',
        ),
        migrations.RemoveField(
            model_name='users',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
        migrations.AddField(
            model_name='users',
            name='client_id',
            field=models.CharField(max_length=10000, null=True, verbose_name='ID клиента'),
        ),
    ]
